title: Dani's Blog
email: machadodaniel.alej@gmail.com
description: >-
  Small blog for my work :D
baseurl: ""
url: "https://Danymach.github.io"
theme: minima

# Show excerpts on homepage
show_excerpts: true

collections:
  projects_ml:
    output: true
    permalink: /ml/projects/:title/
  notes_ml:
    output: true
    permalink: /ml/notes/:title/
  projects_cyber:
    output: true
    permalink: /cyber/projects/:title/
  notes_cyber:
    output: true
    permalink: /cyber/notes/:title/
  projects_qml:
    output: true
    permalink: /qml/projects/:title/
  notes_qml:
    output: true
    permalink: /qml/notes/:title/