title: Daniel's Blog
email: machadodaniel.alej@gmail.com
description: >-
  Small blog for my work.
baseurl: ""
url: "https://yourusername.github.io"
theme: minima

# Show excerpts on homepage
show_excerpts: true